require: rubocop-rails
AllCops:
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'db/schema.rb'
Style/FrozenStringLiteralComment:
  Enabled: false
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 20
